name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  docker-job:
    runs-on: ubuntu-latest
    needs: hello-world-job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log into Azure Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        
      - name: Unique tag for verion
        id: vars
        run: |
          echo "TAG=$(date +'%Y%m%d%H%M')-${{ github.sha }}" >> $GITHUB_ENV  # PS. Use a combo of date+commit SHA for a unique tag

      - name: Build Docker image
        run: docker build -t fatima/musicapi:4.0 ./MusicApi
 
      - name: Tag Docker image
        run: docker tag fatima/musicapi:4.0 ${{ secrets.REGISTRY_URL }}/fatima/musicapi:4.0

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/fatima/musicapi:4.0

      - name: List images
        run: az acr repository list --name ${{ secrets.REGISTRY_NAME }} --output table
