name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8.0.x'

#       - name: Restore dependencies
#         run: dotnet restore ./MusicApi/MusicApi.csproj

#       - name: Build Docker Image
#         run: |
#           echo "Building Docker image..."
#           docker build -t mymusicapi:latest -f MusicApi/Dockerfile .  # Specify the path to the Dockerfile

#       - name: Run Docker Image
#         run: |
#           echo "Running Docker image..."
#           docker run --rm mymusicapi:latest  # Run the Docker image to verify it works
 
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
 
    - uses: actions/checkout@v4
    - name: Build Docker image
      run:  docker build ./MusicApi -t fatima/musicapi
 
    # - name: Checkout code
    #   uses: actions/checkout@v3  # This step checks out your repository's code

    # - name: Build Docker Image
    #   run: |
    #     echo "Building Docker image..."          
    #     docker build -t mymusicapi:latest -f MusicApi/Dockerfile ./MusicApi  # Specify the path to the Dockerfile and context

    # - name: Run Docker Image
    #   run: |
    #     echo "Running Docker image..."
    #     docker run --rm fatima/musicapi 
