name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  docker-job:
    runs-on: ubuntu-latest
    needs: hello-world-job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Azure Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Version tag setup
        id: vars
        run: |
          echo "TAG=$(date +'%Y%m%d%H%M')-${{ github.sha }}" >> $GITHUB_ENV  # Use date+commit SHA for a unique tag

      - name: Building Docker image
        run: docker build -t fatima/musicapi:${{ env.TAG }} ./MusicApi

      - name: Tag Docker image
        run: docker tag fatima/musicapi:${{ env.TAG }} ${{ secrets.REGISTRY_URL }}/fatima/musicapi:${{ env.TAG }}

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/fatima/musicapi:${{ env.TAG }}
