name: Build Docker Image 
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
 
    - uses: actions/checkout@v4
    - name: Build Docker image
      run:  docker build ./MusicApi -t fatima/musicapi
 
    # - name: Checkout code
    #   uses: actions/checkout@v3  # This step checks out your repository's code

    # - name: Build Docker Image
    #   run: |
    #     echo "Building Docker image..."          
    #     docker build -t mymusicapi:latest -f MusicApi/Dockerfile ./MusicApi  # Specify the path to the Dockerfile and context

    - name: Run Docker Image
      run: |
        echo "Running Docker image..."
        docker run --rm musicapi:latest  # Run the Docker image to verify it works
