name: Hello World Build Pipeline

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Run Hello World
        run: echo "Hello, World! The build pipeline has been triggered."  # This prints "Hello, World!"

      - name: Build Project
        run: |
          echo "Building the project..."  # Simulate a build step
          # You can replace this with an actual build command if needed
          echo "Build complete!"  # Indicate the build step is complete
